#!/usr/bin/env bash

set -oue pipefail

if [[ ! -d ~/.config/boxes ]]; then
    mkdir -p ~/.config/boxes
fi

cd ~/.config/boxes
for box in *; do
    name=$(cat $box | head -n 1 | cut -d "[" -f 2 | cut -d "]" -f 1)
    distrobox assemble create --file $box
    distrobox enter $name -- uname -a
    rm ~/.local/share/applications/$name.desktop
done
