#!/usr/bin/env bash

set -oue pipefail

VER=11
VER_FILE=~/.config/ver-dot

if [[ ! -f $VER_FILE ]]; then
    touch $VER_FILE
fi

VER_RAN=$(cat $VER_FILE)

if [[ $VER = "$VER_RAN" ]]; then
    echo "Dotfile manager v$VER has already ran. Exiting..."
    exit 0
fi

mkdir -p ~/.local/bin

echo "Placing config files"
cp -rf /usr/share/timesink/zshrc ~/.zshrc
cp -rf /usr/share/timesink/config/* ~/.config/

echo "Installing shell enhancements"
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#atuin
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#bat
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#fzf
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#fd
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#lsd
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#ripgrep
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#starship
nx profile install github:nixos/nixpkgs/nixpkgs-unstable#zoxide

echo $VER > $VER_FILE
