#!/usr/bin/env bash

set -oue pipefail

images=( $(podman images --format "table {{.Repository}}:{{.Tag}}" --noheading) )

for image in ${images[*]}; do
    podman pull "$image"
    printf "\u2500%.0s" $(seq 1 3) && printf " Pulled $image " && \
        printf "\u2500%.0s" $(seq 1 3) && printf "\n"
done

podman image prune -f
