#!/usr/bin/env bash

set -oue pipefail

read -ra images <<< "$(podman images --format "table {{.Repository}}:{{.Tag}}" --noheading | tr "\n" " ")"

for image in "${images[@]}"; do
    if [[ "$image" != "<none>:<none>" && "$image" != *"localhost"* ]]; then
        podman pull "$image"
        printf "\u2500%.0s" $(seq 1 3) && printf " Pulled %s " "$image" && \
            printf "\u2500%.0s" $(seq 1 3) && printf "\n"
    fi
done

podman image prune -f
podman image prune -f --external
