#!/usr/bin/env bash

set -oue pipefail

FAILED_COMPONENTS=()

log_failure () {
    echo "$COMPONENT upgrade failed" 
    FAILED_COMPONENTS+=( "$COMPONENT" )
}

COMPONENT="bootc"
bootc upgrade ||
    log_failure

COMPONENT="flatpak"
flatpak update -y &&
    flatpak uninstall --unused -y ||
    log_failure

COMPONENT="fwupd"
fwupdmgr -y refresh &&
    fwupdmgr -y get-updates &&
    fwupdmgr -y update ||
    log_failure

if [[ "${FAILED_COMPONENTS[*]}" = "fwupd" ]]; then
    echo "Service has failed upgrading the components: ${FAILED_COMPONENTS[*]}"
    exit 0
elif [[ ! -z ${FAILED_COMPONENTS[*]} ]]; then
    echo "Service has failed upgrading the components: ${FAILED_COMPONENTS[*]}"
    exit 1   
else
    echo "All upgrades applied successfully"
    exit 0
fi
