#!/usr/bin/env bash

set -oue pipefail

notify-send "System Upgrade" "Deploying latest timesinkc image."

FAILED_COMPONENTS=()

log_failure () {
    FAILED_COMPONENTS+=( "$COMPONENT" )
}

draw_sep () {
    printf "\n" && printf "\u2500%.0s" $(seq 1 10) && printf " Updating $COMPONENT " && \
        printf "\u2500%.0s" $(seq 1 20) && printf "\n"
}

COMPONENT="nix"
draw_sep
nx profile upgrade --all ||
    log_failure

COMPONENT="podman"
draw_sep
/usr/libexec/pod-up ||
    log_failure

COMPONENT="distrobox"
draw_sep
distrobox upgrade -a ||
    log_failure

if [[ ! -z ${FAILED_COMPONENTS[*]} ]]; then
    echo "Service has failed upgrading the components: ${FAILED_COMPONENTS[*]}"
    exit 1
else
    echo "All upgrades applied successfully"
    exit 0
fi
