#!/usr/bin/env bash

set -oue pipefail

notify-send -a "timesink upgrade service" "System Upgrade" "Deploying latest timesinkc image."

FAILED_COMPONENTS=()

log_failure () {
    FAILED_COMPONENTS+=( "$COMPONENT" )
}

draw_sep () {
    start=$( (printf "\u2500%.0s" $(seq 1 10) && printf " Updating %s " "$COMPONENT") | wc -c)
    start=$((start + 1))
    printf "\n" && printf "\u2500%.0s" $(seq 1 10) && printf " Updating %s " "$COMPONENT" && \
        printf "\u2500%.0s" $(seq $start 80) && printf "\n"
}

COMPONENT="homebrew"
draw_sep
{ export PATH="${PATH+$PATH:}/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" &&
    hash brew &&
    brew update &&
    brew upgrade -y ; } ||
    log_failure

COMPONENT="nix"
draw_sep
{ export PATH="${PATH+$PATH:}$HOME/.local/bin:$HOME/.local/nix-bin" &&
    hash nix &&
    nix profile upgrade --all --impure ; } ||
    log_failure

COMPONENT="flatpak(user)"
draw_sep
{ flatpak --user update -y &&
    flatpak --user uninstall --unused -y ; } ||
    log_failure

COMPONENT="podman"
draw_sep
/usr/libexec/pod-up ||
    log_failure

COMPONENT="distrobox"
draw_sep
distrobox upgrade -a ||
    log_failure

if [[ -n ${FAILED_COMPONENTS[*]} ]]; then
    echo "Service has failed upgrading the components: ${FAILED_COMPONENTS[*]}"
    exit 1
else
    echo "All upgrades applied successfully"
    exit 0
fi
