#!/usr/bin/env bash

set -oue pipefail

notify-send "System Upgrade" "Deploying latest timesinkc image."

FAILED_COMPONENTS=()

log_failure () {
    echo "$COMPONENT upgrade failed" 
    FAILED_COMPONENTS+=( "$COMPONENT" )
}

COMPONENT="flatpak"
flatpak update -y &&
    flatpak uninstall --unused -y ||
    log_failure

COMPONENT="nix"
nx profile upgrade --all ||
    log_failure

COMPONENT="distrobox"
distrobox upgrade -a ||
    log_failure

if [[ ! -z ${FAILED_COMPONENTS[*]} ]]; then
    echo "Service has failed upgrading the components: ${FAILED_COMPONENTS[*]}"
    exit 1
else
    echo "All upgrades applied successfully"
    exit 0
fi
