name: build-bootc-image
on:
  pull_request:
  schedule:
    - cron: '00 09 * * *'
  push:
      branches:
        - "main"
  workflow_dispatch:

env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions: 
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        major_version: [40]
        desktop: [silverblue]
        build_target: [main, nvidia]
        include:
          - major_version: 40
            is_latest_version: true
            is_stable_version: true

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Gather environment variables
        shell: bash
        run: |
          echo "SOURCE_ORG=fedora-ostree-desktops" >> $GITHUB_ENV
          echo "SOURCE_IMAGE=${{ matrix.desktop }}" >> $GITHUB_ENV

          if [[ "${{ matrix.build_target }}" == "nvidia" ]]; then
            export IMAGE_FLAVOR=nvidia
          else
            export IMAGE_FLAVOR=main
          fi
          echo "IMAGE_NAME=timesinkc-${IMAGE_FLAVOR}" >> $GITHUB_ENV

      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ env.IMAGE_NAME }}

      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          FVER="${{ matrix.major_version }}"
          SRC="${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}"
          TAGS=""
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          TAGS+="${SRC}:pr-${{ github.event.number }}"
          else
            TAGS+="${SRC}:${FVER}"
            TAGS+=",${SRC}:${FVER}-$(date +%Y%m%d)"
            if [[ "${{ matrix.is_latest_version }}" == "true" ]]; then
              TAGS+=",${SRC}:latest"
            fi
            if [[ "${{ matrix.is_stable_version }}" == "true" ]]; then
              TAGS+=",${SRC}:stable"
            fi
          fi
          echo "Publishing with the following tags: "
          echo "${TAGS}"
          
          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@v6
        with:
          file: ./Containerfile
          push: true
          tags: ${{ steps.generate-tags.outputs.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          target: ${{ matrix.build_target }}
          outputs: type=image,compression=zstd,compression-level=11,force-compression=true
          build-args: |
            SOURCE_ORG=${{ env.SOURCE_ORG }}
            SOURCE_IMAGE=${{ env.SOURCE_IMAGE }}
            FEDORA_MAJOR_VERSION=${{ matrix.major_version }}
            IMAGE_FLAVOR=${{ matrix.build_target }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            "AKMOD_PRIVKEY=${{ secrets.AKMOD_PRIVKEY }}"

      - uses: sigstore/cosign-installer@v3.5.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        if: github.event_name != 'pull_request'
        env:
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build_image.outputs.digest }}
